const SET_USER = "SET_USERNAME";
const ADD_MOVIE = "ADD_MOVIE";
const REMOVE_MOVIE = "REMOVE_MOVIE";
const SET_ISNEW = "SET_ISNEW";
const SET_ISROLLED = "SET_ISROLLED";

export { SET_USER, ADD_MOVIE, REMOVE_MOVIE, SET_ISNEW, SET_ISROLLED };
